logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  cloud:
    azure:
      # Properties like spring.cloud.azure.credential.client-id are global properties.
      # Properties like spring.cloud.azure.active-directory.credential.client-id are Microsoft Entra ID properties.
      # If Microsoft Entra ID properties is not configured, global properties will be used.
      #      credential:
      #        client-id:
      #        client-secret:
      #      profile:
      #        tenant-id:
      active-directory:
        b2c:
          enabled: true
          profile:
            tenant-id:
          credential:
            client-id:
          base-uri: https://sb3cookbook.b2clogin.com
          user-flows:
            sign-up-or-sign-in: B2C_1_SISU