spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/football
    username: packt
    password: packt

management:
  endpoints:
    health:
      probes:
        enabled: true
    web:
      exposure:
        include: health,env,metrics,beans,loggers,football
football:
  folder: teams